site_name: elmah.io Blog
site_description: elmah.io Blog with technical posts about elmah.io, ELMAH and .NET related technologies and frameworks.
theme_dir: "mkdocs_bootstrap"
include_next_prev: false
google_analytics: ['UA-42575460-2', 'blog.elmah.io']
site_favicon: favicon.ico
pages:
- Tutorials:
    - 2015 September:
        - Building a salable architecture to handle millions of errors: Building-a-salable-architecture-to-handle-millions-of-errors.md
    - 2015 August:
        - Sending transactional emails using Mandrill and .NET: sending-transactional-emails-using-mandrill-and-net.md
        - Logging to elmah.io from NLog: logging-to-elmah-io-from-nlog.md
        - Umbraco and elmah.io are new best friends: umbraco-and-elmah-io-are-new-best-friends.md
    - 2015 July:
        - Receive an email when a new error is logged: receive-an-email-when-a-new-error-is-logged.md
        - It’s official – elmah.io integrates with Zapier: its-official-elmah-io-integrates-with-zapier.md
    - 2015 June:
        - New mail template: new-mail-template.md
        - Integrate elmah.io with Slack: integrate-elmah-io-with-slack.md
        - Integrate elmah.io with HipChat: integrate-elmah-io-with-hipchat.md
        - How to use Extended User Details even though you don’t use email as user ID: how-to-use-extended-user-details-even-though-you-dont-use-email-as-user-id.md
    - 2015 May:
        - Get better insights with the error occurence graph: get-better-insights-with-the-error-occurence-graph.md
        - Removing sensitive form data before logging to ELMAH: removing-sensitive-form-data-before-logging-to-elmah.md
    - 2015 April:
        - Logging to multiple ELMAH logs: logging-to-multiple-elmah-logs.md
        - Daily Digest Email: daily-digest-email.md
        - Invoicing: invoicing.md
        - API v2 Released: api-v2-released.md
    - 2015 March:
        - Extended User Details: extended-user-details.md
    - 2015 February:
        - Logging custom data to elmah.io: logging-custom-data-to-elmah-io.md
    - 2015 January:
        - Trial accounts introduced: trial-accounts-introduced.md
    - 2014 December:
        - API v2 Beta Released: api-v2-beta-released.md
    - 2014 November:
        - ELMAH Code Snippets for Visual Studio: elmah-code-snippets-for-visual-studio.md
        - elmah.io have been accepted onto Microsoft BizSpark: elmah-io-have-been-accepted-onto-microsoft-bizspark.md
    - 2014 October:
        - How to log errors to ELMAH programmatically: how-to-log-errors-to-elmah-programmatically.md
    - 2014 September:
        - ELMAH vs log4net: elmah-vs-log4net.md
        - Logging to elmah.io through a HTTP proxy: logging-to-elmah-io-through-a-http-proxy.md
    - 2014 June:
        - Introducing the Small Business plan: introducing-the-small-business-plan.md
    - 2014 May:
        - New Feature Burst Protection: new-feature-burst-protection.md
        - New release cycle: new-release-cycle.md
    - 2014 April:
        - Logging from Log4net: logging-to-elmah-io-from-log4net.md
        - We’ve officially launched: weve-officially-launched.md
        - Logging to elmah.io from Serilog: logging-to-elmah-io-from-serilog.md
    - 2014 March:
        - Logging to elmah.io from BlogEngine.NET: logging-to-elmah-io-from-blogengine-net.md
    - 2014 Januar:
        - Logging to elmah.io from Nancy: logging-to-elmah-io-from-nancy.md
    - 2013 December:
        - Logging to elmah.io from ServiceStack: logging-to-elmah-io-from-servicestack.md
        - Running ElasticSearch in a cluster on Azure: running-elasticsearch-in-a-cluster-on-azure.md
        - Using multiple elmah.io logs for different environments: using-multiple-elmah-io-logs-for-different-environments.md
    - 2013 September:
        - ELMAH Elasticsearch Tutorial: elmah-elasticsearch-tutorial.md
    - 2013 August:
        - Another ELMAH tutorial: elmah-tutorial.md
- Otherstuff: 
    - Tuts: category/tutorials/index.md
    - CL: category/changelog/index.md
- Changelog:
    - December 27. 2013: elmah-io-20131227-released.md
    - December 12. 2013: elmah-io-20131212-released.md
    - November 11. 2013: elmah-io-20131111-released.md
    - October 15. 2013: elmah-io-20131015-released.md
    - September 22. 2013: elmah-io-20130922-released.md
    - September 08. 2013: elmah-io-20130908-released.md