site_name: elmah.io docs
site_description: Description of the description
theme_dir: "mkdocs_bootstrap"
include_next_prev: false
pages:
- 2013 September:
    - ELMAH Elasticsearch Tutorial: 2013/09/04/ELMAH Elasticsearch Tutorial.md
- 2013 August:
    - Another ELMAH tutorial: 2013/08/29/another_elmah_tutorial.md