site_name: elmah.io docs
site_description: Description of the description
theme_dir: "mkdocs_bootstrap"
include_next_prev: false
pages:
- Tutorials:
    - 2015 September:
        - Building a salable architecture to handle millions of errors: Building-a-salable-architecture-to-handle-millions-of-errors.md
    - 2015 August:
        - Sending transactional emails using Mandrill and .NET: sending-transactional-emails-using-mandrill-and-net.md
        - Logging to elmah.io from NLog: logging-to-elmah-io-from-nlog.md
        - Umbraco and elmah.io are new best friends: umbraco-and-elmah-io-are-new-best-friends.md
    - 2015 July:
        - Receive an email when a new error is logged: receive-an-email-when-a-new-error-is-logged.md
        - It’s official – elmah.io integrates with Zapier: its-official-elmah-io-integrates-with-zapier.md
    - 2013 December:
        - Running ElasticSearch in a cluster on Azure: running-elasticsearch-in-a-cluster-on-azure.md
    - 2013 September:
        - ELMAH Elasticsearch Tutorial: elmah-elasticsearch-tutorial.md
    - 2013 August:
        - Another ELMAH tutorial: elmah-tutorial.md
- Otherstuff: 
    - Tuts: category/tutorials/index.md
    - CL: category/changelog/index.md
- Changelog:
    - December 27. 2013: elmah-io-20131227-released.md
    - December 12. 2013: elmah-io-20131212-released.md
    - November 11. 2013: elmah-io-20131111-released.md
    - October 15. 2013: elmah-io-20131015-released.md
    - September 22. 2013: elmah-io-20130922-released.md
    - September 08. 2013: elmah-io-20130908-released.md