site_name: elmah.io Blog
site_description: elmah.io Blog with technical posts about elmah.io, ELMAH and .NET related technologies and frameworks.
theme_dir: "mkdocs_bootstrap"
include_next_prev: false
site_favicon: favicon.ico
pages:
- Tutorials:
    - 2016 October:
        - We don't just log your errors. We help you fix them: we-dont-just-log-your-errors-we-help-you-fix-them.md
        - Disable logging: enable-disable-logging.md
    - 2016 September:
        - RevDeBug Available in the Goodie Bag: revdebug-discount-available-in-the-goodiebag.md
        - Deployment Tracking: deployment-tracking.md
        - Improved Message Grouping: improved-message-grouping.md
        - Decorating errors with version number using Azure Websites: decorating-errors-with-version-number-using-azure-websites.md
        - Restructuring Plans and Pricing: restructuring-plans-and-pricing.md
        - Writing custom error loggers for ELMAH: writing-custom-error-loggers-for-elmah.md
        - New Features for App Store Developers: new-features-for-appstore-developers.md
    - 2016 August:
        - Usage Monitoring: usage-monitoring.md
        - Support for Logary: support-for-logary.md
        - Permanent link to search results: permanent-link-to-search-results.md
        - ELMAH security and allowRemoteAccess explained: elmah-security-and-allowremoteaccess-explained.md
        - Bulk managing users in an organisation: bulk-managing-users-in-an-organisation.md
        - Filtering Errors by IP Addresses: filtering-errors-by-ip-addresses.md
        - ASP.NET Core Status: aspnet-core-status.md
        - Infinite Scroll (Well Almost): infinite-scroll-well-almost.md
    - 2016 July:
        - Support for .NET and ASP.NET Core: support-for-dotnet-and-aspnet-core.md
        - Organization Support: organization-support.md
    - 2016 June:
        - .NET Logging Tools and Libraries: dot-net-logging-tools-and-libraries.md
        - Installation Help Directly Inside elmah.io: installation-help-directly-inside-elmah-io.md
    - 2016 May:
        - Ignore Errors Generated by Bots: ignore-errors-generated-by-bots.md
    - 2016 April:
        - Redesigned Dashboard with Drag and Drop: redesigned-dashboard-with-drag-and-drop.md
    - 2016 March:
        - Adding Version Information to your Log: adding-version-information-to-your-log.md
        - ELMAH Configuration Validator: elmah-configuration-validator.md
        - The ELMAH Schema: the-elmah-schema.md
        - 10 Improvements in 10 Days Roundup: ten-improvements-in-ten-days-roundup.md
        - ELMAH Security Validator: improvement-ten-elmah-security-validator.md
        - MyGet Discount Available in the Goodie Bag: improvement-nine-myget-discount-available-in-the-goodie-bag.md
        - An Even Better Toolbar: improvement-eight-an-even-better-toolbar.md
        - User Agent View: improvement-seven-user-agent-view.md
    - 2016 February:
        - Nicely Formatted Dates: improvement-six-nicely-formatted-dates.md
        - Status Code with a Vengeance: improvement-five-status-codes-with-a-vengeance.md
        - Compact Toolbar: improvement-four-compact-toolbar.md
        - Two new and fun products in the Goodie bag: improvement-three-two-new-and-fun-products-in-the-goodie-bag.md
        - Increased session timeout: improvement-two-increased-session-timeout.md
        - HTTP method on URLs: improvement-one-http-method-on-urls.md
        - 10 Improvements in 10 Days: ten-improvements-in-ten-days.md
    - 2016 January:
        - The elmah.io AppStore: elmah-io-appstore.md
    - 2015 December:
        - Discounts on popular .NET tools with the elmah.io Goodie Bag: discounts-on-popular-net-tools-with-the-elmah-io-goodie-bag.md
        - elmah.io Technology Stack: elmah-io-technology-stack.md
        - Yearly Subscriptions: yearly-subscriptions.md
        - ASP.NET Error Logging Best Practices: asp-net-error-logging-best-practices.md
    - 2015 September:
        - Danish service provides maximum scaling and secures data on Azure: danish-service-provides-maximum-scaling-and-secures-data-on-azure.md
        - elmah.io documentation: elmah-io-documentation.md
        - Building a salable architecture to handle millions of errors: Building-a-salable-architecture-to-handle-millions-of-errors.md
    - 2015 August:
        - Sending transactional emails using Mandrill and .NET: sending-transactional-emails-using-mandrill-and-net.md
        - Logging to elmah.io from NLog: logging-to-elmah-io-from-nlog.md
        - Umbraco and elmah.io are new best friends: umbraco-and-elmah-io-are-new-best-friends.md
    - 2015 July:
        - Receive an email when a new error is logged: receive-an-email-when-a-new-error-is-logged.md
        - It’s official – elmah.io integrates with Zapier: its-official-elmah-io-integrates-with-zapier.md
    - 2015 June:
        - New mail template: new-mail-template.md
        - Integrate elmah.io with Slack: integrate-elmah-io-with-slack.md
        - Integrate elmah.io with HipChat: integrate-elmah-io-with-hipchat.md
        - How to use Extended User Details even though you don’t use email as user ID: how-to-use-extended-user-details-even-though-you-dont-use-email-as-user-id.md
    - 2015 May:
        - Get better insights with the error occurence graph: get-better-insights-with-the-error-occurence-graph.md
        - Removing sensitive form data before logging to ELMAH: removing-sensitive-form-data-before-logging-to-elmah.md
    - 2015 April:
        - Logging to multiple ELMAH logs: logging-to-multiple-elmah-logs.md
        - Daily Digest Email: daily-digest-email.md
        - Invoicing: invoicing.md
        - API v2 Released: api-v2-released.md
    - 2015 March:
        - Extended User Details: extended-user-details.md
    - 2015 February:
        - Logging custom data to elmah.io: logging-custom-data-to-elmah-io.md
    - 2015 January:
        - Trial accounts introduced: trial-accounts-introduced.md
    - 2014 December:
        - API v2 Beta Released: api-v2-beta-released.md
    - 2014 November:
        - ELMAH Code Snippets for Visual Studio: elmah-code-snippets-for-visual-studio.md
        - elmah.io have been accepted onto Microsoft BizSpark: elmah-io-have-been-accepted-onto-microsoft-bizspark.md
    - 2014 October:
        - How to log errors to ELMAH programmatically: how-to-log-errors-to-elmah-programmatically.md
    - 2014 September:
        - ELMAH vs log4net: elmah-vs-log4net.md
        - Logging to elmah.io through a HTTP proxy: logging-to-elmah-io-through-a-http-proxy.md
    - 2014 August:
        - Logging to elmah.io from JavaScript using JSNLog: logging-to-elmah-io-from-javascript-using-jsnlog.md
        - Great new features for our paying customers: great-new-features-for-our-paying-customers.md
    - 2014 July:
        - Say hello to the redesigned Overview: say-hello-to-the-redesigned-overview.md
        - Introducing the new Visual Studio extension: introducing-the-new-visual-studio-extension.md
        - Unlimited logs now available on all paid plans: unlimited-logs-now-available-on-all-paid-plans.md
    - 2014 June:
        - Introducing the Small Business plan: introducing-the-small-business-plan.md
    - 2014 May:
        - New Feature Burst Protection: new-feature-burst-protection.md
        - New release cycle: new-release-cycle.md
    - 2014 April:
        - Logging from Log4net: logging-to-elmah-io-from-log4net.md
        - We’ve officially launched: weve-officially-launched.md
        - elmah.io 20140412 released: elmah-io-20140412-released.md
        - Logging to elmah.io from Serilog: logging-to-elmah-io-from-serilog.md
    - 2014 March:
        - elmah.io 20140315 released: elmah-io-20140315-released.md
        - Logging to elmah.io from BlogEngine.NET: logging-to-elmah-io-from-blogengine-net.md
    - 2014 February:
        - elmah.io 20140219 released: elmah-io-20140219-released.md
    - 2014 Januar:
        - Logging to elmah.io from Nancy: logging-to-elmah-io-from-nancy.md
    - 2013 December:
        - elmah.io 20131227 released: elmah-io-20131227-released.md
        - Logging to elmah.io from ServiceStack: logging-to-elmah-io-from-servicestack.md
        - Running ElasticSearch in a cluster on Azure: running-elasticsearch-in-a-cluster-on-azure.md
        - elmah.io 20131212 released. 2013: elmah-io-20131212-released.md
        - Using multiple elmah.io logs for different environments: using-multiple-elmah-io-logs-for-different-environments.md
    - 2013 November:
        - Logging errors to elmah.io: logging-errors-to-elmah-io.md
        - elmah.io 20131111 released: elmah-io-20131111-released.md
    - 2013 October:
        - elmah.io 20131015 released: elmah-io-20131015-released.md
    - 2013 September:
        - elmah.io 20130922 released: elmah-io-20130922-released.md
        - Logging custom errors to elmah.io: logging-custom-errors-to-elmah-io.md
        - Configuring elmah.io from code: configuring-elmah-io-from-code.md
        - Logging to elmah.io from Web API: logging-to-elmah-io-from-web-api.md
        - elmah.io 20130908 released: elmah-io-20130908-released.md
        - ELMAH Elasticsearch Tutorial: elmah-elasticsearch-tutorial.md
    - 2013 August:
        - ELMAH tutorial: elmah-tutorial.md
- Otherstuff: 
    - Tuts: category/tutorials/index.md
    - CL: category/changelog/index.md
    - Docs: index.md
    - FAQ: faq.md
